owner: CORDTOWN
repo: status

sites:
  - name: 오픈예정
    url: https://go.cord.town/telegram

status-website:
  cname: status.cord.town
  logoUrl: https://raw.githubusercontent.com/CORDTOWN/status/master/assets/logo_black_trans.png
  name: CORDTOWN Status
  introTitle: "**Upptime** for CORD TOWN"
  introMessage: 안전하고 매력적인 커뮤니티 🏠
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://go.cord.town/website
    - title: Discord
      href: https://go.cord.town/discord
      
